GET  http://localhost:3000/api/v1/academic-faculties



GET  http://localhost:3000/api/v1/academic-faculties/67e3b67e204f1bb5a7f19267



DELETE http://localhost:3000/api/v1/academic-faculties/67e3b6cb204f1bb5a7f19273


PATCH  http://localhost:3000/api/v1/academic-faculties/67e3b67e204f1bb5a7f19267
Content-Type: application/json
{
    "name": "testingg"
}



POST http://localhost:3000/api/v1/academic-faculties/create-academic-faculty
Content-Type: application/json
{
    "name": "Bangla"
}


